services:
  banco:
    image: postgis/postgis:16-3.4
    container_name: enchentes_banco
    environment:
      POSTGRES_USER: enchentes
      POSTGRES_PASSWORD: enchentes
      POSTGRES_DB: enchentes
    ports:
      - "5432:5432"
    volumes:
      - banco_dados:/var/lib/postgresql/data

volumes:
  banco_dados:
